export const FETCH_WEATHER_ERROR='FETCH_WEATHER_ERROR';
export const FETCH_WEATHER_SUCCESS='FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_START='FETCH_WEATHER_START';
export const FETCH_WEATHER_END='FETCH_WEATHER_END';

export const ADD_FAVORITE='ADD_FAVORITE';
export const CLEAR_FAVORITES='CLEAR_FAVORITES';
export const TOGGLE_FAVORITES='TOGGLE_FAVORITES';

export const FAVORITES_FROM_LOCAL_STORAGE='FAVORITES_FROM_LOCAL_STORAGE';